export const GAME_STATE = {
    NEW_GAME: "NEW_GAME",
    PLAYING: "PLAYING",
    BANKER_OFFER: "BANKER_OFFER",
    GAME_OVER: "GAME_OVER",
};

export const BANKER_OFFER_TRIGGERS = [6, 11, 15, 18, 20, 22, 24];
